//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSDBEntities : DbContext
    {
        public CMSDBEntities()
            : base("name=CMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Ayarlar> tbl_Ayarlar { get; set; }
        public virtual DbSet<tbl_Icerik> tbl_Icerik { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_KullaniciGrubu> tbl_KullaniciGrubu { get; set; }
        public virtual DbSet<tbl_Tags> tbl_Tags { get; set; }
        public virtual DbSet<tbl_Yorum> tbl_Yorum { get; set; }
        public virtual DbSet<tbl_Izinler> tbl_Izinler { get; set; }
    }
}
