//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Kullanici()
        {
            this.tbl_Icerik = new HashSet<tbl_Icerik>();
        }
    
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string AdiSoyadi { get; set; }
        public string EPosta { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public bool AktifDurumu { get; set; }
        public string Resim { get; set; }
        public int KullaniciGrupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Icerik> tbl_Icerik { get; set; }
        public virtual tbl_KullaniciGrubu tbl_KullaniciGrubu { get; set; }
    }
}
