//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yorum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Yorum()
        {
            this.tbl_Yorum1 = new HashSet<tbl_Yorum>();
        }
    
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string Yorum { get; set; }
        public int Puan { get; set; }
        public Nullable<int> UstId { get; set; }
        public int IcerikId { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public bool AktifDurumu { get; set; }
        public int BegeniSayisi { get; set; }
        public int BegenmemeSayisi { get; set; }
    
        public virtual tbl_Icerik tbl_Icerik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yorum> tbl_Yorum1 { get; set; }
        public virtual tbl_Yorum tbl_Yorum2 { get; set; }
    }
}
