//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Izinler
    {
        public int Id { get; set; }
        public string KontrollerAdi { get; set; }
        public int Yetkiler { get; set; }
        public int KullaniciGrubuId { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public bool AktifDurumu { get; set; }
    
        public virtual tbl_KullaniciGrubu tbl_KullaniciGrubu { get; set; }
    }
}
