//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIOCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Icerik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Icerik()
        {
            this.tbl_Icerik1 = new HashSet<tbl_Icerik>();
            this.tbl_Yorum = new HashSet<tbl_Yorum>();
            this.tbl_Tags = new HashSet<tbl_Tags>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public string Url { get; set; }
        public string Resim { get; set; }
        public Nullable<int> UstId { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public bool AktifDurumu { get; set; }
        public int KullaniciId { get; set; }
        public int OnayDurumu { get; set; }
        public int IcerikTipi { get; set; }
        public int OkunmaSuresi { get; set; }
        public int OkunmaSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Icerik> tbl_Icerik1 { get; set; }
        public virtual tbl_Icerik tbl_Icerik2 { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Yorum> tbl_Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tags> tbl_Tags { get; set; }
    }
}
